// Lista de frases y elementos visuales asociados
const frasesYElementos = [

    { frase: "Una rosa para otra rosa 🌹" },
    { frase: "¡Brilla como una estrella! ⭐" },
    { frase: "Un corazón para ti ❤️" },
    { frase: "Un toque de magia ✨" },
    { frase: "Abraza el momento 🤗" },
    { frase: "Sueña en grande 🌈" },
    { frase: "Cada día es una nueva oportunidad 🌅" },
    { frase: "Lucha por tus sueños 💪" },
    { frase: "Cree en ti mismo 🙌" },
    { frase: "Tu sonrisa ilumina el mundo 😊" },
    { frase: "Haz que cada segundo cuente ⏳" },
    { frase: "El amor está en el aire 💖" },
    { frase: "La felicidad es una elección 😄" },
    { frase: "Atrévete a ser diferente 🚀" },
    { frase: "La paciencia es clave 🔑" },
    { frase: "El cielo es el límite ☁️" },
    { frase: "Sigue tus sueños 💭" },
    { frase: "Encuentra la belleza en lo simple 🌻" },
    { frase: "Eres increíble 💫" },
    { frase: "Confía en el proceso 🌱" },
    { frase: "Haz lo que amas y ama lo que haces 💖" },
    { frase: "Cada paso cuenta 👣" },
    { frase: "Un día a la vez 🌄" },
    { frase: "Ser feliz es una elección 😊" },
    { frase: "No te rindas, el éxito está cerca 💪" },
    { frase: "Las pequeñas cosas importan 🦋" },
    { frase: "Tu historia es única 📖" },
    { frase: "Rodéate de buenas vibras ✨" },
    { frase: "Sigue adelante 🌈" },
    { frase: "Eres más fuerte de lo que piensas 💥" },
    { frase: "La vida es un regalo 🎁" },
    { frase: "Disfruta cada momento 🎉" },
    { frase: "El tiempo es oro ⏳" },
    { frase: "Sé amable siempre 🧡" },
    { frase: "La aventura te espera 🧭" },
    { frase: "Todo es posible 💫" },
    { frase: "Eres tu mejor versión 🌟" },
    { frase: "Sonríe más, preocúpate menos 😊" },
    { frase: "Cree en los milagros ✨" },
    { frase: "Elige ser feliz 💖" },
    { frase: "Tu actitud marca la diferencia 🌞" },
    { frase: "Sigue tus intuiciones 💭" },
    { frase: "Eres especial 💫" },
    { frase: "La magia está en los pequeños detalles 🌟" },
    { frase: "Valora cada momento ❤️" },
    { frase: "Escucha a tu corazón 💖" },
    { frase: "El éxito es una decisión 💼" },
    { frase: "Es tu momento de brillar 🌠" },
    { frase: "Rodéate de personas que te hagan mejor 💬" },
    { frase: "Cada sonrisa cuenta 😊" },
    { frase: "Todo lo que necesitas está en ti 🙌" },
    { frase: "Sé tu propio héroe 🦸‍♀️🦸‍♂️" },
    { frase: "No hay límites cuando crees en ti 🔝" },
    { frase: "Haz más de lo que te hace feliz 🥳" },
    { frase: "La vida es mejor con una sonrisa 😊" },
    { frase: "Comparte amor 💌" },
    { frase: "La confianza en ti es el primer paso ✨" },
    { frase: "Cada día es una oportunidad de ser feliz 🌞" },
    { frase: "Elige lo que te hace brillar ✨" },
    { frase: "Ríe sin parar 😂" },
    { frase: "El poder está en tu mente 💭" },
    { frase: "Sé el cambio que deseas ver 🌍" },
    { frase: "Cree en lo imposible 🌠" },
    { frase: "Escucha tu voz interior 🧘‍♀️" },
    { frase: "Valora a quienes te rodean 🫂" },
    { frase: "Eres más fuerte cada día 💪" },
    { frase: "Abraza el cambio 🌈" },
    { frase: "Eres un rayo de sol 🌞" },
    { frase: "Aprovecha cada oportunidad 🌟" },
    { frase: "La vida es un viaje, disfrútalo 🚀" },
    { frase: "Dale sentido a cada día 💫" },
    { frase: "Estás creando tu historia 📝" },
    { frase: "Sé tú mismo, todos los demás están ocupados 🤩" },
    { frase: "Recuerda, eres amado 💖" },
    { frase: "El futuro es brillante ✨" },
    { frase: "Las mejores cosas vienen cuando menos lo esperas 🌠" },
    { frase: "La gratitud es la clave 🥂" },
    { frase: "Comparte tu luz 🌟" },
    { frase: "No temas a los nuevos comienzos 🌱" },
    { frase: "Sé luz para los demás 💡" },
    { frase: "Tu esfuerzo valdrá la pena 💪" },
    { frase: "Lo mejor está por venir 🌄" },
    { frase: "Tienes el poder de crear 🛠️" },
    { frase: "Haz que tus sueños se hagan realidad ✨" },
    { frase: "Encuentra paz en tu interior 🕊️" },
    { frase: "Ama cada momento ❤️" },
    { frase: "Nunca es tarde para empezar de nuevo 🕰️" },
    { frase: "Tu potencial es ilimitado 🌌" },
    { frase: "La vida es una aventura 🌄" },
    { frase: "Confía en el camino 🛤️" },
    { frase: "Sonríe siempre, es gratis 😄" },
    { frase: "Cada día trae una nueva oportunidad 🌅" },
    { frase: "Tus sueños importan 💭" },
    { frase: "Eres más valiente de lo que crees 🦁" },
    { frase: "Sigue adelante con fuerza 💪" },
    { frase: "El amor propio es el mejor amor ❤️" },
    { frase: "Disfruta las pequeñas cosas 🌸" },
    { frase: "Tu viaje es único 🌍" },
    { frase: "La alegría es contagiosa 😂" },
    { frase: "Vive sin arrepentimientos 🎢" },
    { frase: "Eres el héroe de tu historia 📖" },
    { frase: "La vida es lo que tú haces de ella 🌱" },
    { frase: "Sé amable, siempre ❤️" },
    { frase: "Tienes todo lo necesario dentro de ti 🙌" },
    { frase: "Todo pasa por algo 🌅" },
    { frase: "Rodéate de amor y positividad 💖" },
    { frase: "Hoy es un buen día para sonreír 😊" },
    { frase: "Encuentra el equilibrio 🌿" },
    { frase: "Escucha a tu intuición ✨" },
    { frase: "Tú decides tu destino 🔮" },
    { frase: "El éxito es tuyo si trabajas por él 🌠" },
    { frase: "Elige la paz 🕊️" },
    { frase: "No dejes de creer en ti 💪" },
    { frase: "La esperanza es el mejor comienzo 🌈" },
    { frase: "Tu tiempo es ahora ⏰" },
    { frase: "Valora cada momento ⌛" },
    { frase: "Abraza tus talentos 🎨" },
    { frase: "El amor es la respuesta ❤️" },
    { frase: "Tus palabras tienen poder ✍️" },
    { frase: "Haz que cada día cuente 📆" },
    { frase: "La paciencia es una virtud 🌱" },
    { frase: "Sé auténtico 🕵️‍♀️" },
    { frase: "Nunca subestimes tu capacidad 🏋️" },
    { frase: "Lo mejor está por suceder 🌠" },
    { frase: "Eres un milagro en este mundo 🌎" },
    { frase: "Cada paso te acerca a tu meta 🎯" },
    { frase: "Rodéate de luz 💡" },
    { frase: "Todo lo bueno toma tiempo ⏳" },
    { frase: "Comparte tu energía positiva ✨" },
    { frase: "Haz que el mundo sea mejor 🌍" },
    { frase: "Sonríe, el universo te observa 🌌" },
    { frase: "La grandeza está en lo simple 🌿" },
    { frase: "Inspira a otros a ser mejores ✨" },
    { frase: "Eres más que suficiente 🌟" },
    { frase: "Hazlo con amor y dedicación 💖" },
    { frase: "Encuentra la paz en el presente 🕊️" },
    { frase: "Eres el cambio 🌈" },
    { frase: "Amar es vivir ❤️" },
    { frase: "La vida es un sueño 🎠" },
    { frase: "Gracias por estar aquí 🫂" },
    { frase: "Sigue siempre adelante 💪" },
    { frase: "A rose for another rose 🌹" },
    { frase: "Shine like a star ⭐" },
    { frase: "A heart for you ❤️" },
    { frase: "A touch of magic ✨" },
    { frase: "Embrace the moment 🤗" },
    { frase: "Dream big 🌈" },
    { frase: "Every day is a new chance 🌅" },
    { frase: "Fight for your dreams 💪" },
    { frase: "Believe in yourself 🙌" },
    { frase: "Your smile lights up the world 😊" },
    { frase: "Make every second count ⏳" },
    { frase: "Love is in the air 💖" },
    { frase: "Happiness is a choice 😄" },
    { frase: "Dare to be different 🚀" },
    { frase: "Patience is key 🔑" },
    { frase: "The sky is the limit ☁️" },
    { frase: "Follow your dreams 💭" },
    { frase: "Find beauty in simplicity 🌻" },
    { frase: "You are amazing 💫" },
    { frase: "Trust the process 🌱" },
    { frase: "The best is yet to come 🌟" },
    { frase: "Stay positive 🌞" },
    { frase: "Believe in the magic of new beginnings ✨" },
    { frase: "Let the adventure begin 🏞️" },
    { frase: "You are capable of amazing things 💥" },
    { frase: "Be the change you want to see 🌍" },
    { frase: "Create your own sunshine 🌞" },
    { frase: "Don't just exist, live 🌱" },
    { frase: "Be yourself, everyone else is already taken 😎" },
    { frase: "Youve got this 💪" },
    { frase: "The only limit is your mind 🧠" },
    { frase: "Wake up and be awesome 🌞" },
    { frase: "Keep going, keep growing 🌳" },
    { frase: "Life is beautiful 🌸" },
    { frase: "Today is a good day to start something new 🌱" },
    { frase: "Every moment is a fresh beginning 🌅" },
    { frase: "Dont wait for opportunity, create it 🔨" },
    { frase: "Live the life youve imagined 🌟" },
    { frase: "Success is not final, failure is not fatal 💼" },
    { frase: "The journey is the destination 🛤️" },
    { frase: "You are stronger than you think 💪" },
    { frase: "Believe in your dreams 🌙" },
    { frase: "Happiness is homemade 🏡" },
    { frase: "Life is short, make it sweet 🍭" },
    { frase: "Good things take time ⏳" },
    { frase: "You are your only limit 🚀" },
    { frase: "Success starts with self-belief 🌟" },
    { frase: "Don't stop until you're proud 🙌" },
    { frase: "Your vibe attracts your tribe ✨" },
    { frase: "Live every day like it's your last 🎉" },
    { frase: "Take it easy, and enjoy the ride 🚗" },
    { frase: "Let your dreams be your wings 🦋" },
    { frase: "Hard work beats talent when talent doesn't work hard 💼" },
    { frase: "Be the best version of yourself 🌟" },
    { frase: "Do more of what makes you happy 🎉" },
    { frase: "Follow your heart ❤️" },
    { frase: "Youre only one decision away from a completely different life 🔄" },
    { frase: "Make today count ⏰" },
    { frase: "Everything you can imagine is real 🎨" },
    { frase: "Live with passion 🔥" },
    { frase: "Be kind to yourself 💖" },
    { frase: "You are enough 🌸" },
    { frase: "Turn your dreams into plans 🗺️" },
    { frase: "Don't let anyone dull your sparkle ✨" },
    { frase: "Find joy in the journey 🚀" },
    { frase: "When nothing goes right, go left ⬅️" },
    { frase: "Trust the timing of your life ⏳" },
    { frase: "Its a good day to have a good day ☀️" },
    { frase: "Be grateful for today 🙏" },
    { frase: "You are the artist of your own destiny 🎨" },
    { frase: "Dream it, wish it, do it ✨" },
    { frase: "Take a deep breath and keep going 💨" },
    { frase: "The best is yet to come 🌟" },
    { frase: "Its never too late to be what you might have been ⏳" },
    { frase: "Every new beginning comes from some other beginning's end 💭" },
    { frase: "Start where you are. Use what you have. Do what you can 💪" },
    { frase: "Enjoy the little things 🍃" },
    { frase: "Believe in your power 💫" },
    { frase: "Stay humble, hustle hard 💼" },
    { frase: "Make your dreams happen 💫" },
    { frase: "Good vibes only ✌️" },
    { frase: "Focus on the good 🌟" },
    { frase: "You are the energy you attract ⚡" },
    { frase: "Let go and grow 🌱" },
    { frase: "Be brave, be bold 💥" },
    { frase: "Don't dream your life, live your dream 🌟" },
    { frase: "Your potential is endless 🌌" },
    { frase: "The best way to predict the future is to create it 🛠️" },
    { frase: "Stay strong, the weekend is coming 💪" },
    { frase: "Life is a beautiful struggle 🌻" },
    { frase: "Go after your dreams with determination 💫" },
    { frase: "Keep calm and stay positive 🌞" },
    { frase: "Take chances, make mistakes 🔄" },
    { frase: "You are what you believe 🧠" },
    { frase: "Stop wishing, start doing 🏁" },
    { frase: "Live without regrets ✨" },
    { frase: "Do it with passion or not at all 💖" },
    { frase: "Dont be afraid to fail, be afraid not to try ⚡" },
    { frase: "Good things are coming, just wait 🌟" },
    { frase: "Be your own hero 🦸" },
    { frase: "You are unstoppable 💪" },
    { frase: "The future belongs to those who believe in the beauty of their dreams 🌈" },
    { frase: "Everything happens for a reason 🌱" },
    { frase: "The best revenge is massive success 💼" },
    { frase: "Enjoy every moment ⏳" },
    { frase: "The world is full of beautiful things, just look around 👀" },
    { frase: "Life is too important to be taken seriously 🎭" },
    { frase: "You have the power to change your life 🌟" },
    { frase: "Happiness looks good on you 😄" },
    { frase: "Your journey starts now 🛤️" },
    { frase: "Believe you can, and youre halfway there 🚀" },
    { frase: "You are the creator of your own destiny 🌱" },
    { frase: "Let it go and move forward 💨" },
    { frase: "The magic happens outside of your comfort zone ✨" },
    { frase: "You are stronger than you think 💪" },
    { frase: "Dont just wish for it, work for it 🔨" },
    { frase: "Keep the faith, everything will be okay 🙏" },
    { frase: "Success is the best revenge 💼" },
    { frase: "Today is your day ✨" },
    { frase: "Be proud of how far youve come 💪" },
    { frase: "Make today amazing 🌟" },
    { frase: "The time for action is now ⏳" },
    { frase: "Live with intention, not by accident 💭" },
    { frase: "You can do hard things 💥" },
    { frase: "Start where you are and take small steps 👣" },
    { frase: "Dream big, work hard, stay focused 💪" },
    { frase: "You are capable of great things ✨" },
    { frase: "Let your light shine 🌟" },
    { frase: "Uma rosa para outra rosa 🌹" },
    { frase: "Brilhe como uma estrela ⭐" },
    { frase: "Um coração para você ❤️" },
    { frase: "Um toque de magia ✨" },
    { frase: "Abrace o momento 🤗" },
    { frase: "Sonhe grande 🌈" },
    { frase: "Cada dia é uma nova oportunidade 🌅" },
    { frase: "Lute pelos seus sonhos 💪" },
    { frase: "Acredite em si mesmo 🙌" },
    { frase: "Seu sorriso ilumina o mundo 😊" },
    { frase: "Faça cada segundo contar ⏳" },
    { frase: "O amor está no ar 💖" },
    { frase: "A felicidade é uma escolha 😄" },
    { frase: "Ouse ser diferente 🚀" },
    { frase: "A paciência é a chave 🔑" },
    { frase: "O céu é o limite ☁️" },
    { frase: "Siga seus sonhos 💭" },
    { frase: "Encontre beleza na simplicidade 🌻" },
    { frase: "Você é incrível 💫" },
    { frase: "Confie no processo 🌱" },
    { frase: "A vida é curta, aproveite ao máximo 🌟" },
    { frase: "O impossível é só uma opinião 💬" },
    { frase: "A persistência leva à conquista 🏆" },
    { frase: "Viva o momento 🎉" },
    { frase: "Acredite em sua jornada ✨" },
    { frase: "A felicidade começa com você 😊" },
    { frase: "Você é a sua maior inspiração 💖" },
    { frase: "Nada é impossível, a palavra diz tudo 💬" },
    { frase: "Sonhe, acredite, realize ✨" },
    { frase: "Sorria, você está vivendo 😁" },
    { frase: "A vida é feita de escolhas 🛤️" },
    { frase: "Seja sua melhor versão 💪" },
    { frase: "A gratidão transforma tudo 🙏" },
    { frase: "A vida é o que você faz dela 🌻" },
    { frase: "O futuro é agora ⏳" },
    { frase: "Nada é mais poderoso do que a mente 💡" },
    { frase: "A vitória é de quem acredita 🏅" },
    { frase: "O segredo é nunca desistir 🔑" },
    { frase: "Seja a mudança que você quer ver no mundo 🌍" },
    { frase: "Não tenha medo de recomeçar 🔄" },
    { frase: "Cada dia é um novo começo 🌅" },
    { frase: "O sucesso é resultado de muito esforço 💪" },
    { frase: "Quem não tenta, não vence 🏅" },
    { frase: "A paciência traz grandes resultados ⏳" },
    { frase: "Faça com amor e paixão ❤️" },
    { frase: "Viva seus sonhos, não os seus medos 🌈" },
    { frase: "Acredite na magia da vida ✨" },
    { frase: "As grandes conquistas começam com pequenos passos 👣" },
    { frase: "A beleza está nos olhos de quem vê 👀" },
    { frase: "A vida é feita de desafios 🏆" },
    { frase: "Seu potencial é ilimitado 🚀" },
    { frase: "Não pare até se orgulhar 👏" },
    { frase: "Você é mais forte do que imagina 💪" },
    { frase: "Cada desafio é uma oportunidade 💡" },
    { frase: "O melhor ainda está por vir 🌟" },
    { frase: "Tudo é possível se você acreditar ✨" },
    { frase: "A sua felicidade depende de você 😄" },
    { frase: "A gratidão é a chave para a felicidade 🔑" },
    { frase: "A vida é 10% o que acontece e 90% como reagimos 💭" },
    { frase: "Acredite nos seus sonhos e faça acontecer 🌟" },
    { frase: "Você é capaz de realizar grandes feitos 💫" },
    { frase: "O impossível é apenas uma opinião 💬" },
    { frase: "Seja a luz que você quer no mundo 💡" },
    { frase: "O sucesso começa com uma atitude positiva 🙌" },
    { frase: "A felicidade é uma decisão diária 😊" },
    { frase: "A única forma de fazer um bom trabalho é amando o que faz ❤️" },
    { frase: "Seja grato por tudo, até pelos desafios 🙏" },
    { frase: "A melhor maneira de prever o futuro é criá-lo 🔮" },
    { frase: "O sorriso é a melhor maquiagem 👑" },
    { frase: "Viva sem arrependimentos 🌿" },
    { frase: "Acredite que você pode e você já está no meio do caminho 💪" },
    { frase: "Os melhores momentos são feitos de pequenas coisas 🌸" },
    { frase: "A vida é feita de escolhas, escolha ser feliz 😄" },
    { frase: "Apenas se permita ser quem você é ✨" },
    { frase: "Cada novo começo vem de algum outro começo 💫" },
    { frase: "Transforme seus sonhos em metas 🌠" },
    { frase: "Você é mais do que capaz de conquistar seus sonhos 💭" },
    { frase: "Desafios fazem você mais forte 💪" },
    { frase: "A felicidade é feita de momentos simples 🌷" },
    { frase: "Seja o melhor de você todos os dias 💎" },
    { frase: "A vida começa onde termina sua zona de conforto 🏡" },
    { frase: "Acredite que você é capaz de coisas incríveis 🌈" },
    { frase: "A vida é como um espelho, sorria para ela 😄" },
    { frase: "O segredo é nunca desistir, por mais difícil que seja 🔑" },
    { frase: "Seu maior concorrente é você mesmo 👑" },
    { frase: "Siga em frente, o sucesso está logo ali 🌟" },
    { frase: "A mente é tudo, você se torna aquilo que pensa 💭" },
    { frase: "Viva cada dia como se fosse o último 💫" },
    { frase: "O que você faz hoje pode mudar sua vida para sempre 🔮" },
    { frase: "Nada é impossível para quem acredita ✨" },
    { frase: "O primeiro passo para o sucesso é acreditar em si mesmo 🙌" },
    { frase: "Seja fiel a você mesmo 💖" },
    { frase: "Cada erro é uma lição aprendida 📚" },
    { frase: "Sorria, a vida é bela 😊" },
    { frase: "O sucesso é a soma de pequenos esforços repetidos 👊" },
    { frase: "Confiança é a chave para o sucesso 🔑" },
    { frase: "Coragem é saber o que fazer, mesmo quando temos medo 🦁" },
    { frase: "Quando você acredita, nada é impossível ✨" },
    { frase: "A vida é feita de escolhas, escolha ser feliz 🌟" },
    { frase: "A verdadeira felicidade está dentro de você 💖" },
    { frase: "Você é capaz de conquistar tudo o que desejar 💪" },
    { frase: "Acredite no seu potencial 🌟" },
    { frase: "Faça a diferença na vida das pessoas 🌍" },
    { frase: "Cada dia é uma nova chance para ser melhor 🌱" },
    { frase: "O maior erro é não tentar 💡" },
    { frase: "Seja grato pelas pequenas coisas 🌸" },
    { frase: "Você é incrível, não duvide disso 💫" },
    { frase: "Não desista, o sucesso pode estar mais perto do que você imagina 🏆" },
    { frase: "A vida é feita de escolhas, escolha ser feliz 😄" },
    { frase: "Cada passo que você dá é uma conquista 🏅" },
    { frase: "A verdadeira beleza vem de dentro 💖" },
    { frase: "Tudo o que você precisa está dentro de você 🌱" },
    { frase: "Acredite que você pode e você já está no meio do caminho 💪" },
    { frase: "A felicidade é um estado de espírito 🧘‍♀️" },
    { frase: "Nunca pare de acreditar em seus sonhos 💭" },
    { frase: "A gratidão transforma o que temos em suficiente 🙏" },
    { frase: "Seja a razão pela qual alguém sorri hoje 😊" },
    { frase: "A melhor maneira de predizer o futuro é criá-lo 💫" },
    { frase: "Transforme seus sonhos em realidade ✨" },
    { frase: "O céu é o limite, agora voe alto 🚀" },
    { frase: "O que você faz hoje reflete seu amanhã ⏳" }
];


let frasesMostradas = []; // Array para llevar control de las frases que ya se mostraron

// Función para mostrar la frase en pantalla
function mostrarFrase() {
    if (frasesMostradas.length === frasesYElementos.length) {
        frasesMostradas = []; // Resetear si todas las frases se mostraron
    }

    let indiceAleatorio;
    do {
        indiceAleatorio = Math.floor(Math.random() * frasesYElementos.length); // Selección aleatoria
    } while (frasesMostradas.includes(indiceAleatorio)); // Evitar repetir frases

    frasesMostradas.push(indiceAleatorio); // Marcar la frase como mostrada

    const frasesContainer = document.getElementById("frases-container");
    frasesContainer.innerHTML = ""; // Limpiar frases anteriores

    const fraseElement = document.createElement("div");
    fraseElement.className = "frase";
    fraseElement.innerText = frasesYElementos[indiceAleatorio].frase;

    // Establecer posición aleatoria
    const posicionAleatoria = obtenerPosicionAleatoria(fraseElement.offsetWidth, fraseElement.offsetHeight);
    fraseElement.style.position = "absolute"; // Asegúrate de que sea absoluta
    fraseElement.style.left = `${posicionAleatoria.left}px`;
    fraseElement.style.top = `${posicionAleatoria.top}px`;

    frasesContainer.appendChild(fraseElement);

    // Animar la aparición de la frase
    setTimeout(() => {
        fraseElement.style.opacity = 1;
    }, 100); // Aparece inmediatamente

    // Mantener la frase visible por 3 segundos
    setTimeout(() => {
        fraseElement.style.opacity = 0;
    }, 3000); // Mantener la frase por 3 segundos antes de desvanecer
}

// Función para obtener una posición aleatoria en la pantalla
function obtenerPosicionAleatoria(anchoFrase, altoFrase) {
    const anchoPantalla = window.innerWidth;
    const altoPantalla = window.innerHeight;
    const margen = 50; // Margen para evitar que las frases se salgan de la pantalla

    // Generar coordenadas aleatorias dentro de los límites de la pantalla
    const left = Math.random() * (anchoPantalla - anchoFrase - 2 * margen) + margen;
    const top = Math.random() * (altoPantalla - altoFrase - 2 * margen) + margen;

    return { left, top };
}